[build]
providers = ["node"]

[phases.setup]
nixPackages = ["nodejs_18", "npm"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build:safe"

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
